function net=addCompactTS(net, projDim, nc, learnW, dataset)
    TS_obj = yang_compact_bilinear_TS_nopool_2stream(projDim, [nc nc], 1);

    wf=consts(dataset, 'projInitW', 'projDim', projDim, 'cfgId', 'compact2');
    if exist(wf, 'file') ==2
        fprintf('loading an old compact2 weight\n');
        load(wf);
        % modify the initialized parameters to the loaded params 
        TS_obj.h_={hs(1,:), hs(2,:)};
        TS_obj.weights_={ss(1,:), ss(2,:)};
        TS_obj.setSparseM(TS_obj.weights_, 1);
    end
    
    net.layers{end+1}=struct('type', 'custom',...
        'layerObj', TS_obj, ...
        'forward', @TS_obj.forward_simplenn, ...
        'backward', @TS_obj.backward_simplenn, ...
        'name', 'compact_TS', ...
        'outDim', projDim, ...
        'weights', {{cat(1, TS_obj.weights_{:})}}, ...
        'learningRate', [1]*learnW);
end