function net=addBilinear(net)
    net.layers{end+1}=struct('type', 'custom',...
        'forward', @yang_bilinear_forward, ...
        'backward', @yang_bilinear_backward, ...
        'name', 'bilinear');
end