function net=addFisher(net, dataset, network, use448, batchSize)
    clear yang_fv
    % currently fix the number of mixtures=64, 
    init_param=train_GMM_and_get_fisher_vector_v2(...
               dataset, network, 64, use448, net, batchSize);
    
    net.layers{end+1}=struct('type','custom',...
        'init_param', {init_param},...
        'forward', @yang_fv_forward,...
        'backward',@yang_fv_backward,...
        'name', 'fisher_layer');
end